### ISSUE TITLE
Please Keep More Info how to do it

### ISSUE THREAD

**Issue by canopyone** [docxtor/docxtor#1]
can we add a html template  and generate a word document with header and footer ?

**Comment by vyorkin** [comment]
If you mean using an html template as a source for building a word document the short answer is no. Headers & footers is not supported too unfortunately.

For now if you really want html templates, headers and footers you can try [docxtor](https://github.com/jafrog/docxtor).  These two gems will become just one in the nearest future (may be in a week or 2) with support for both: dsl and html templates. And we have plans to add some must-have features, including custom document templates, dynamic styling, dsl for headers & footers, tables, lists, images, etc. We are working on it in collaboration with [jafrog](https://github.com/jafrog), she's a maintainer of docxtor gem, so don't hesitate to submit an issue if you have any troubles with it.

Here's an example of basic usage for docxtor2: [gist6359406](https://gist.github.com/vyorkin/6359406)
Please note that doxtor2 supports only ree 1.8.7 and mri 1.8.7 rubies, docxtor has 1.9 branch that support mri 1.9.x
