### ISSUE TITLE
integration test error

### ISSUE THREAD

**Issue by qinfanpeng** [docxtor/docxtor#3]
While i'm run integration test, there two failure as follow. Can you help me? many thanks!
![_001](https://f.cloud.github.com/assets/2350557/1232574/b7d01f5a-28cd-11e3-81b9-47c9e54b767b.png)

**Comment by jafrog** [comment]
Hi! What's your Ruby version? For now we've tested Docxtor only with Ruby 1.8.7.

**Comment by vyorkin** [comment]
closed coz of inactivity for 4 years lol
